# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Paul R. Decker

# A plugin is supplied explicitly. Normal public builds never inspect or fetch it.
option(WFG_ENABLE_ENCODER_PLUGINS "Compile user-supplied waveform encoders" OFF)
set(WFG_ENCODER_PLUGIN_DIR "" CACHE PATH "Directory containing wfg-plugin.cmake")
if(WFG_ENABLE_ENCODER_PLUGINS)
    if(NOT WFG_ENCODER_PLUGIN_DIR OR NOT EXISTS "${WFG_ENCODER_PLUGIN_DIR}/wfg-plugin.cmake")
        message(FATAL_ERROR "Encoder plugins enabled: set WFG_ENCODER_PLUGIN_DIR to a module containing wfg-plugin.cmake")
    endif()
    get_filename_component(WFG_ENCODER_PLUGIN_DIR "${WFG_ENCODER_PLUGIN_DIR}" ABSOLUTE)
    include("${WFG_ENCODER_PLUGIN_DIR}/wfg-plugin.cmake")
    if(NOT WFG_ENCODER_PLUGIN_SOURCES)
        message(FATAL_ERROR "wfg-plugin.cmake must provide WFG_ENCODER_PLUGIN_SOURCES")
    endif()
    foreach(source IN LISTS WFG_ENCODER_PLUGIN_SOURCES)
        if(NOT IS_ABSOLUTE "${source}" OR NOT EXISTS "${source}")
            message(FATAL_ERROR "Plugin source must be an existing absolute path: ${source}")
        endif()
    endforeach()
endif()

function(wfg_attach_encoder_plugin target)
    if(MSVC)
        target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:/fp:strict>)
    else()
        target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-ffp-contract=off;-fno-fast-math>)
    endif()
    target_sources(${target} PRIVATE "${WFG_ROOT}/waveform-source/encoder_registry.cpp")
    if(WFG_ENABLE_ENCODER_PLUGINS)
        target_sources(${target} PRIVATE ${WFG_ENCODER_PLUGIN_SOURCES})
        target_include_directories(${target} PRIVATE ${WFG_ENCODER_PLUGIN_INCLUDE_DIRS})
        target_compile_definitions(${target} PRIVATE WFG_ENABLE_ENCODER_PLUGINS=1)
    endif()
endfunction()
